export { default as Assignment } from "./assignment";
export { default as Call } from "./call";
export { default as Command } from "./command";
export { default as Comment } from "./comment";
export { default as Elif } from "./elif";
export { default as Else } from "./else";
export { default as End } from "./end";
export { default as If } from "./if";
export { default as Ifs } from "./ifs";
